#!/bin/sh
set -e

echo "Removing user datim_auto_cert_updater and its home directory...";
sudo deluser --remove-home datim_auto_cert_updater || true

# this is taken care of automatically when `purge` is run instead of `remove`
#echo "Removing all installed files...";
#sudo rm -r /usr/share/datim-auto-cert-updater || true
#sudo rm -r /etc/cron.d/datim-auto-cert-updater || true
#sudo rm -r /etc/sudoers.d/datim-auto-cert-updater || true

exit 0



