#!/bin/sh
set -e


# this is taken care of automatically when `purge` is run instead of `remove`
#echo "Removing all installed files...";
#sudo rm -r /usr/share/datim-auto-cert-updater || true
#sudo rm -r /etc/cron.d/datim-auto-cert-updater || true
#sudo rm -r /etc/sudoers.d/datim-auto-cert-updater || true

exit 0



