#!/bin/sh
set -e

#echo "Enabling execution on renewal check script...";
sudo chmod +x /usr/share/datim-auto-cert-updater/check_for_renewal.sh
sudo chmod +x /usr/share/datim-auto-cert-updater/update_dependencies_post_renewal.sh
sudo chmod +x /usr/share/datim-auto-cert-updater/restart_dependencies_post_update.sh
#ls -l /usr/share/datim-auto-cert-updater/check_for_renewal.sh
sudo service sudo restart

exit 0
