#!/bin/sh
set -e
echo "Enabling execution on renewal check script...";
sudo chmod +x /usr/share/datim4u-auto-cert-updater/check_for_renewal.sh
ls -l /usr/share/datim4u-auto-cert-updater/check_for_renewal.sh
exit 0