#!/bin/sh

# create updater user, under whom cron job will run
echo "Creating user datim4u_auto_cert_updater and its home directory...";
sudo useradd -d /home/datim4u_auto_cert_updater -m datim4u_auto_cert_updater || true
